//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUXUAT
    {
        public string MaPX { get; set; }
        public string MaSP { get; set; }
        public string MaKH { get; set; }
        public Nullable<float> SoLuong { get; set; }
        public Nullable<System.DateTime> Ngayxuat { get; set; }
        public Nullable<System.DateTime> Gioxuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
    }
}
