//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public string MaPN { get; set; }
        public string MaSP { get; set; }
        public Nullable<float> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public string Ghichu { get; set; }
    
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
