//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGSANXUAT
    {
        public string MaHSX { get; set; }
        public string MaSP { get; set; }
        public string MaNCC { get; set; }
        public string TenHSX { get; set; }
        public string XuatXu { get; set; }
        public string MoTa { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
