//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.HANGSANXUATs = new HashSet<HANGSANXUAT>();
        }
    
        public string MaSP { get; set; }
        public string MaHSX { get; set; }
        public string TenSP { get; set; }
        public string MaNCC { get; set; }
        public string MaLoaiSP { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string TinhTrang { get; set; }
        public string Mausac { get; set; }
        public string Thongsochitiet { get; set; }
        public string Mota { get; set; }
        public Nullable<int> Baohanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGSANXUAT> HANGSANXUATs { get; set; }
    }
}
